WITH T1 AS
(
	SELECT
	CUST AS CUSTOMER,
	PROD AS PRODUCT,
	MAX(QUANT) AS OCT_MAX
	FROM SALES
	WHERE MONTH = 10
	AND YEAR > 2017
	GROUP BY CUST,PROD
),
T2 AS 
(
	SELECT
	T1.CUSTOMER,T1.PRODUCT,T1.OCT_MAX,
	S.DATE AS OCT_DATE
	FROM T1,SALES AS S
	WHERE T1.OCT_MAX = S.QUANT
	AND MONTH = 10
	AND YEAR > 2017
	AND T1.CUSTOMER = S.CUST
	AND T1.PRODUCT = S.PROD
),
T3 AS
(
	SELECT
	CUST AS CUSTOMER,
	PROD AS PRODUCT,
	MIN(QUANT) AS NOV_MIN
	FROM SALES
	WHERE MONTH = 11
	GROUP BY CUST,PROD
),
T4 AS 
(
	SELECT
	T3.CUSTOMER,T3.PRODUCT,T3.NOV_MIN,
	S.DATE AS NOV_DATE
	FROM T3,SALES AS S
	WHERE T3.NOV_MIN = S.QUANT
	AND MONTH = 11
	AND T3.CUSTOMER = S.CUST
	AND T3.PRODUCT = S.PROD
),
T5 AS
(
	SELECT
	CUST AS CUSTOMER,
	PROD AS PRODUCT,
	MIN(QUANT) AS DEC_MIN
	FROM SALES
	WHERE MONTH = 12
	GROUP BY CUST,PROD
),
T6 AS 
(
	SELECT
	T5.CUSTOMER,T5.PRODUCT,T5.DEC_MIN,
	S.DATE AS DEC_DATE
	FROM T5,SALES AS S
	WHERE T5.DEC_MIN = S.QUANT
	AND MONTH = 12
	AND T5.CUSTOMER = S.CUST
	AND T5.PRODUCT = S.PROD
),
T7 AS
(
	SELECT T2.CUSTOMER,T2.PRODUCT,T2.OCT_MAX,T2.OCT_DATE,T4.NOV_MIN,T4.NOV_DATE
	FROM T2 FULL JOIN T4 
	ON T2.CUSTOMER = T4.CUSTOMER
	AND T2.PRODUCT = T4.PRODUCT
)
SELECT 
	T7.CUSTOMER,T7.PRODUCT,T7.OCT_MAX,
	T7.OCT_DATE,T7.NOV_MIN,T7.NOV_DATE,
	T6.DEC_MIN,T6.DEC_DATE
FROM T7 JOIN T6
ON T7.CUSTOMER = T6.CUSTOMER
AND T7.PRODUCT = T6.PRODUCT