WITH T1 AS
(
	SELECT MONTH,PROD,SUM(QUANT) 
	FROM SALES
	GROUP BY MONTH,PROD
),
T2 AS
(
	SELECT MONTH,MAX(SUM),MIN(SUM)
	FROM T1
	GROUP BY MONTH
),
T3 AS
(
	SELECT T2.MONTH,
		T1.PROD AS MOST_POPULAR_PROD,
		T2.MAX AS MOST_POP_TOTAL_Q,
		T2.MIN AS LEAST_POP_TOTAL_Q
	FROM T2,T1
	WHERE T2.MONTH = T1.MONTH
	AND T2.MAX = T1.SUM
)
SELECT T3.MONTH,
	T3.MOST_POPULAR_PROD,
	T3.MOST_POP_TOTAL_Q,
	T1.PROD AS LEAST_POPULAR_PROD,
	T3.LEAST_POP_TOTAL_Q
FROM T3,T1
WHERE T3.MONTH = T1.MONTH
AND T3.LEAST_POP_TOTAL_Q = T1.SUM