WITH T1 AS
(
	SELECT DISTINCT PROD AS PRODUCT,MONTH,SUM(QUANT)FROM SALES GROUP BY PROD,MONTH
),
T2 AS
(
	SELECT PRODUCT,MAX(SUM),MIN(SUM) FROM T1 GROUP BY PRODUCT
),
T3 AS
(
	SELECT T2.PRODUCT,T1.MONTH AS MOST_FAV_MO,T2.MIN
	FROM T2,T1
	WHERE T2.PRODUCT = T1.PRODUCT
	AND T2.MAX = T1.SUM
)
SELECT
	T3.PRODUCT,
	T3.MOST_FAV_MO,
	T1.MONTH AS LEAST_FAV_MO
FROM T3,T1
WHERE T3.PRODUCT = T1.PRODUCT
AND T3.MIN = T1.SUM