WITH CT AS
(
	SELECT PROD,CUST,ROUND(AVG(QUANT),0) AS CT_AVG
	FROM SALES WHERE 
	YEAR BETWEEN 2016 AND 2020
	AND STATE = 'CT'
	GROUP BY CUST,PROD
),
NY AS
(
	SELECT PROD,CUST,ROUND(AVG(QUANT),0) AS NY_AVG
	FROM SALES WHERE 
	YEAR BETWEEN 2016 AND 2020
	AND STATE = 'NY'
	GROUP BY CUST,PROD
),
NJ AS
(
	SELECT PROD,CUST,ROUND(AVG(QUANT),0) AS NJ_AVG
	FROM SALES WHERE 
	YEAR BETWEEN 2016 AND 2020
	AND STATE = 'NJ'
	GROUP BY CUST,PROD
),
PA AS
(
	SELECT PROD,CUST,ROUND(AVG(QUANT),0) AS PA_AVG
	FROM SALES WHERE 
	YEAR BETWEEN 2016 AND 2020
	AND STATE = 'PA'
	GROUP BY CUST,PROD
),
AVG AS
(
	SELECT PROD,CUST,ROUND(AVG(QUANT),0) AS AVERAGE
	FROM SALES WHERE 
	YEAR BETWEEN 2016 AND 2020
	GROUP BY CUST,PROD
),
TOTAL AS
(
	SELECT PROD,CUST,SUM(QUANT) AS TOTAL
	FROM SALES WHERE 
	YEAR BETWEEN 2016 AND 2020
	GROUP BY CUST,PROD
),
COUNT AS
(
	SELECT PROD,CUST,COUNT(QUANT) AS COUNT
	FROM SALES WHERE 
	YEAR BETWEEN 2016 AND 2020
	GROUP BY CUST,PROD
)
SELECT
	TOTAL.PROD AS PRODUCT,
	TOTAL.CUST AS CUSTOMER,
	CT.CT_AVG,NY.NY_AVG,NJ.NJ_AVG,PA.PA_AVG,
	AVG.AVERAGE,TOTAL.TOTAL,COUNT.COUNT
FROM (((((TOTAL JOIN CT ON TOTAL.PROD = CT.PROD AND TOTAL.CUST = CT.CUST)
	JOIN NY ON TOTAL.PROD = NY.PROD AND TOTAL.CUST = NY.CUST)
	JOIN NJ ON TOTAL.PROD = NJ.PROD AND TOTAL.CUST = NJ.CUST)
	JOIN PA ON TOTAL.PROD = PA.PROD AND TOTAL.CUST = PA.CUST)
	JOIN AVG ON TOTAL.PROD = AVG.PROD AND TOTAL.CUST = AVG.CUST)
	JOIN COUNT ON TOTAL.PROD = COUNT.PROD AND TOTAL.CUST = COUNT.CUST